# Generated by Django 5.2.1 on 2025-05-27 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='follow',
            name='last_notified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
