# Generated by Django 5.2.1 on 2025-05-29 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_follow_last_notified_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='follow',
            name='last_notified_at',
        ),
    ]
