# Generated by Django 5.2.1 on 2025-05-29 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_notification_is_seen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('follow', 'Follow'), ('comment', 'Comment'), ('like', 'Like')], max_length=20),
        ),
    ]
