# Generated by Django 5.2.1 on 2025-09-23 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_alter_userprofile_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('comment', 'Comment'), ('like', 'Like')], max_length=20),
        ),
        migrations.DeleteModel(
            name='Follow',
        ),
    ]
