services:
    - type: web
      name: coverence-backend
      env: python
      plan: free
      buildCommand: pip install -r src/coverence/requirements.txt && python manage.py collectstatic --noinput
      startCommand: daphne -b 0.0.0.0 -p 10000 coverence.asgi:application
      workingDir: src/coverence
      autoDeploy: true
      envVars:
          - key: DJANGO_SETTINGS_MODULE
            value: coverence.settings
          - key: SECRET_KEY
            value: "django-insecure-!8(jr$b@j-s^c!x08*s#laji8-1nmu$+r9h@5!ym3n^1e##$4o"
          - key: DEBUG
            value: False
          - key: ALLOWED_HOSTS
            value: coverence-backend.onrender.com
          - key: REDIS_URL
            value: redis://default:LwW8o9g09EvBfQHrrDnxEe2ERBZusBJJ@redis-10112.c11.us-east-1-2.ec2.redns.redis-cloud.com:10112
          - key: PORT
            value: 10000
