# Generated by Django 5.2.1 on 2025-06-11 22:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_message_is_seen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='is_seen',
        ),
    ]
